GET http://localhost:3001/api/users/65f2a5527a250eecb33aac1d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlciIsImlkIjoiNjVmMmE1NTI3YTI1MGVlY2IzM2FhYzFkIiwiaWF0IjoxNzEwNDA2NTQwfQ.kS-U6qaUPyXDj1BFht3AwSJCt3UljbBDBxVtt-vGCsg

